---
- name: Installing httpd & apache2  packages
  hosts: webservers
  become: true

  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: starting httpd service
    service:
      name: htt
      state: started
    when:  ansible_os_family == "RedHat"
    ignore_errors: yes 

  - name: Installing apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: starting apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copying a file
    copy:
      src: /home/ansible/index.html 
      dest: /var/www/html
      mode: 0666
    

