---
- name: Installing httpd  packages
  hosts: webservers
  become: true

  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: installed
    notify: starting httpd service
      
  handlers:
  - name: starting httpd service
    service:
      name: httpd
      state: started

