---
- name: Uninstalling httpd  package
  hosts: webservers
  become: true

  tasks:

  - name: stopping httpd service
    service:
      name: httpd
      state: stopped

  - name: Uninstalling httpd
    yum:
      name: httpd
      state: removed

